I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 740, in script
    show rod sup at center with Shake(0.5, 10) # 罗德里克（惊讶）并震动，使用Ren'Py内置的Shake
  File "game/script.rpy", line 740, in <module>
    show rod sup at center with Shake(0.5, 10) # 罗德里克（惊讶）并震动，使用Ren'Py内置的Shake
NameError: name 'Shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 740, in script
    show rod sup at center with Shake(0.5, 10) # 罗德里克（惊讶）并震动，使用Ren'Py内置的Shake
  File "/Users/yanfengwu/renpy-8.3.3/renpy/ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "/Users/yanfengwu/renpy-8.3.3/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/yanfengwu/renpy-8.3.3/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 740, in <module>
    show rod sup at center with Shake(0.5, 10) # 罗德里克（惊讶）并震动，使用Ren'Py内置的Shake
NameError: name 'Shake' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.3.24111502
Decipher 1.0
Tue May 27 22:42:00 2025
